### ISSUE TITLE
Create first class way to right align a column and its header

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux-ag-grid#32]
Sky 1, our vanilla grid (pending dev work), and grids on the AG Grid demo have a way to make the column and its content right aligned. We should have this ability in our AG Grid as well

**Comment by Tdortiz** [comment]
## Overview
Just briefly looking into to help out and brainstorm some ideas.

Headers
- Looks like the simplest approach would be to expose constant of a modified header template that right aligns the header.
- In my example below it would be encapsulating the `headerComponentParams.template` into an exported const.

Cells
- We could highlight in documentation that we can simply add `'text-align': 'right'` to the column def. 
  - We could also provide a constant that people could import that is `'text-align': 'right'`.
- We could also create a Cell Renderer that allows consumers to pass in a parameter on how to align the content (aligns text left, right, center). 

---

## Column Cells
For column cells AG Grid does have a way to apply styles to the cell with the . Here we can use `cellStyle: { 'text-align': 'right' }`.

```js
{
  colId: 'Amount',
  field: 'amount',
  headerName: 'Amount',
  headerTooltip: 'The invoice's amount',
  cellStyle: { 'text-align': 'right' },
  sortable: false
}
```

---

## Column Headers

- [Header Templates](https://www.ag-grid.com/javascript-grid-column-header/#header-templates)
  - The default template is the first code block at the link.
  - > You can provide a header template used by the default header component for simple layout changes
- [Custom Header Components](https://www.ag-grid.com/javascript-grid-column-header/#customHeader)
  - > If you want to change the behaviour, please look at creating your own component


Note the `eLabel` element which has the custom flex-box styling.
```
{
  colId: 'Amount',
  field: 'amount',
  headerName: 'Amount',
  headerTooltip: 'The invoice's amount',
  cellStyle: { 'text-align': 'right' },
  sortable: false,
  headerComponentParams: {
    template: `
      <div class="ag-cell-label-container" role="presentation">
        <span ref="eMenu" class="ag-header-icon ag-header-cell-menu-button"></span>
        <div ref="eLabel" class="ag-header-cell-label" style="display: flex; justify-content: flex-end; align-items: center;" role="presentation">
          <span ref="eText" class="ag-header-cell-text" role="columnheader"></span>
          <span ref="eFilter" class="ag-header-icon ag-filter-icon"></span>
          <span ref="eSortOrder" class="ag-header-icon ag-sort-order"></span>
          <span ref="eSortAsc" class="ag-header-icon ag-sort-ascending-icon"></span>
          <span ref="eSortDesc" class="ag-header-icon ag-sort-descending-icon"></span>
          <span ref="eSortNone" class="ag-header-icon ag-sort-none-icon"></span>
        </div>
      </div>`
  }
}

```

Results of the cell style and column template are below in the amount column.

![image](https://user-images.githubusercontent.com/10877317/81713479-ebeb2f80-9443-11ea-8336-19d89a15ba67.png)
