### ISSUE TITLE
Need dropdown in SkyCellType 

### ISSUE THREAD

**Issue by KhanUmairKhan** [blackbaud/skyux-ag-grid#55]
As we all know dropdown is one of the most frequently used control , and data entry grid is not providing it. I have tried it to create through cellRendererFramework , I was able to create it but some default functionalities were not working properly like :tabbing.

So please add this.

[AB#1540642](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1540642)

**Comment by Blackbaud-ErikaMcVey** [comment]
Do you need a dropdown like a context menu, or an HTML select field? The SKY dropdown component is intended to be used as a menu, but you could use a generic select field input, SKY autocomplete, SKY lookup, or SKY select to select a specific value.

When you tried to implement it, what issue did you see with the tabbing?

**Comment by KhanUmairKhan** [comment]
I need it as a HTML select field.

Problem 1: If I am keeping ColDef editable option true , tab button is moving focus to the next cell correctly but
when i click on cell my select field is getting replaced by input.
Problem 2: If I am keeping ColDef editable option false, my select field is working fine but cell is not getting focused on click of tab.

**Comment by Blackbaud-RakeshGarg** [comment]
We also need SkyCellType.Dropdown as part of Registered columnTypes for Edit mode.

**Comment by Blackbaud-RakeshGarg** [comment]
Can add SkyCellType.Dropdown as part of Registered columnTypes. Please
