### ISSUE TITLE
Ability to not sort columns when using skyAgGridDataManagerAdapter directive

### ISSUE THREAD

**Issue by Sean-Blackbaud** [blackbaud/skyux-ag-grid#67]
Columns are in alphabetical order by default when using the skyAgGridDataManagerAdapter directive on a sky-data-view.

My team would like to use our own order with the more frequently used columns appearing first.

Please add the ability to not perform any sorting.

[AB#1542176](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1542176)

**Comment by Blackbaud-DanMiller** [comment]
Fixed by https://github.com/blackbaud/skyux-data-manager/pull/12
