### ISSUE TITLE
With paging enabled, clicking on the paging bar or the horizontal scroll scrolls to the top of the grid

### ISSUE THREAD

**Issue by Sean-Blackbaud** [blackbaud/skyux-ag-grid#69]
Reproduce steps:
  1. Have a grid with large enough column widths to make the horizontal scroll bar appear.
  2. Enable paging on the gridOptions (pagination: true)
  3. Scroll to the bottom of the grid and attempt to use the horizontal scroll bar to move to the right
   
Instead of scrolling, I'm having the whole grid scroll to the top.  Clicking on the paging bar does the same thing including clicking to the 

next page, but the event will fire at least so the next page will be displayed.

I SUSPECT that sky-ag-grid-wrapper is using the skyBackToTop directive and that it's overlayed onto the horizontal scroll and paging bars.

![2020-08-12_12-38-33](https://user-images.githubusercontent.com/48290872/90042552-d7b00c00-dc98-11ea-9dcf-d2b17a830595.gif)

[AB#1551340](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1551340)

**Comment by Sean-Blackbaud** [comment]
Oh and just to note, removing the sky-ag-grid-wrapper from my ag-grid-angular does fix the issue so I presume it must be related to the wrapper.

**Comment by Blackbaud-SteveBrush** [comment]
If I comment-out this line, it works: https://github.com/blackbaud/skyux-ag-grid/blob/master/src/app/public/modules/ag-grid/ag-grid-wrapper.component.ts#L77

**Comment by Sean-Blackbaud** [comment]
> If I comment-out this line, it works: https://github.com/blackbaud/skyux-ag-grid/blob/master/src/app/public/modules/ag-grid/ag-grid-wrapper.component.ts#L77

Nice
