### ISSUE TITLE
Need maximum characters restriction in SkyCellType.Text and SkyCellType.Number

### ISSUE THREAD

**Issue by suuyashgupta** [blackbaud/skyux-ag-grid#79]
Can we add an restriction of maximum characters that can be entered by user for text and number cell types in ag-Grid?

We need it in one of the feature that we are implementing in Blackbaud Grantmaking Application. The only alternative today is to create our own custom cell editors but we don't want to create the custom cell editors of data types, for which SKYUX's cell editor is already available.

[AB#1583254](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1583254)

**Comment by Blackbaud-SteveBrush** [comment]
For MVP, let's simply disallow the user from entering more characters as they type.
