### ISSUE TITLE
Headers aren't sticky when grid is used in a modal

### ISSUE THREAD

**Issue by brianbianchi** [blackbaud/skyux-ag-grid#80]
Expected: (Image of when grid is not in a modal)
![image](https://user-images.githubusercontent.com/8227748/94207246-36ba9080-fe95-11ea-8c86-c3264798b4d9.png)

Actual: (Image of grid when it is in a modal)
![image](https://user-images.githubusercontent.com/8227748/94207348-6cf81000-fe95-11ea-85b0-f83f8b804115.png)

[AB#1585825](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1585825)

**Comment by jennifermullen** [comment]
Hello, do we have an update on this? Thank you.

**Comment by Blackbaud-KerryCampbell** [comment]
this is being tracked in [ADO](https://dev.azure.com/blackbaud/Products/_workitems/edit/1585825)
