### ISSUE TITLE
Keyboard navigation / grid api context using the master detail grid

### ISSUE THREAD

**Issue by brianbianchi** [blackbaud/skyux-ag-grid#81]
This issue manifests in several ways when using a [master detail grid](https://www.ag-grid.com/javascript-grid-master-detail/).

One example:
When initially rendering a grid, immediately open a master detail grid. Enter a value and then tab as if to enter a value in the next column. The user is unable to select and enter edit mode in the adjacent cell using keyboard shortcuts.
![image](https://user-images.githubusercontent.com/8227748/94318869-72b62a00-ff57-11ea-8c38-db6c41db4ab5.png)
If the user then selects a cell in the overall grid, the grid will visually look like two cells are selected, and the keyboard navigation will be broken.
![image](https://user-images.githubusercontent.com/8227748/94319145-04259c00-ff58-11ea-9bfd-d7625656d4dd.png)

I _think_ what is happening is the wrapper is _only_ selecting and using the overall grid API for navigation, status bar selection, etc. The issue is not happening when I remove the SKYUX  wrapper.

You can use this demo site to see the issue.
https://host.nxt.blackbaud.com/distributions-demo/

[AB#1587406](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1587406)

**Comment by jennifermullen** [comment]
Hello, do we have an update on this? Thank you.
