### ISSUE TITLE
Styling for agRichSelectCellEditor is not supported

### ISSUE THREAD

**Issue by brianbianchi** [blackbaud/skyux-ag-grid#89]
Trying to implement [agRichSelectCellEditor](https://www.ag-grid.com/javascript-grid-provided-cell-editors/#agrichselectcelleditor) in my grid. The grid column names disappear and the styling doesn't look to be correct.

I am using this as an alternative to a possible `SkyCellType.Dropdown`.

![image](https://user-images.githubusercontent.com/8227748/100912399-66da6d00-349e-11eb-968a-af607cc0f0b5.png)

**Comment by Blackbaud-SteveBrush** [comment]
Closing, we recommend using a SKY UX component within a custom cell editor.
