### ISSUE TITLE
Add support for the ag-Grid "checkboxSelection" grid option.

### ISSUE THREAD

**Issue by Blackbaud-StacyCarlos** [blackbaud/skyux-ag-grid#97]
The row selector cell renderer currently doesn't respect ag-Grid's `checkboxSelection` [grid option](https://www.ag-grid.com/documentation/angular/row-selection/#checkbox-selection).

[AB#1695589](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1695589)

**Comment by Blackbaud-AshleyGabriel** [comment]
Can you please provide more information? Thanks!

**Comment by Blackbaud-StacyCarlos** [comment]
This ag-Grid option, linked above, can be used to conditionally remove the ability to select rows using ag-Grid's native row selection. I would assume that the row selector component in this library is meant to be used as the standard SKY implementation of that native functionality. As such, I would assume it would support this option if the need for it arose.

**Comment by Blackbaud-AshleyGabriel** [comment]
Hi Stacy - can you please fill out this issue in ADO and answer the questions in the template? That will help us better understand and prioritize. Thanks so much! [https://dev.azure.com/blackbaud/Products/_workitems/create/Feature?templateId=553e8cbd-12ff-4e72-a44f-e47e2de5f0a8&ownerId=26bb0bf6-45ac-482d-b33e-02e252c297e3]

**Comment by Blackbaud-MichaelCollier** [comment]
Closing in GitHub we have the issue filed in ADO.
